# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientSensorView.ui'
#
# Created: Sun Apr 17 15:00:37 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Sensor(object):
    def setupUi(self, Sensor):
        Sensor.setObjectName(_fromUtf8("Sensor"))
        Sensor.resize(700, 230)
        self.centralwidget = QtGui.QWidget(Sensor)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 191, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pushButtonConnect = QtGui.QPushButton(self.groupBox)
        self.pushButtonConnect.setGeometry(QtCore.QRect(10, 110, 75, 23))
        self.pushButtonConnect.setObjectName(_fromUtf8("pushButtonConnect"))
        self.pushButtonDeconnect = QtGui.QPushButton(self.groupBox)
        self.pushButtonDeconnect.setGeometry(QtCore.QRect(100, 110, 75, 23))
        self.pushButtonDeconnect.setObjectName(_fromUtf8("pushButtonDeconnect"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 160, 80))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEditPort = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditPort.setObjectName(_fromUtf8("lineEditPort"))
        self.gridLayout.addWidget(self.lineEditPort, 1, 1, 1, 1)
        self.lineEditIP = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditIP.setObjectName(_fromUtf8("lineEditIP"))
        self.gridLayout.addWidget(self.lineEditIP, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(230, 40, 421, 171))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.pushButtonSend = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonSend.setGeometry(QtCore.QRect(330, 140, 75, 23))
        self.pushButtonSend.setObjectName(_fromUtf8("pushButtonSend"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 18, 401, 111))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEditX = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditX.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditX.setObjectName(_fromUtf8("lineEditX"))
        self.gridLayout_2.addWidget(self.lineEditX, 3, 0, 1, 1)
        self.lineEditA = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditA.setObjectName(_fromUtf8("lineEditA"))
        self.gridLayout_2.addWidget(self.lineEditA, 3, 3, 1, 1)
        self.pushButtonCM = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonCM.setObjectName(_fromUtf8("pushButtonCM"))
        self.gridLayout_2.addWidget(self.pushButtonCM, 2, 6, 1, 1)
        self.pushButtonZP = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonZP.setObjectName(_fromUtf8("pushButtonZP"))
        self.gridLayout_2.addWidget(self.pushButtonZP, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 5, 1, 1)
        self.pushButtonZM = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonZM.setObjectName(_fromUtf8("pushButtonZM"))
        self.gridLayout_2.addWidget(self.pushButtonZM, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 3, 1, 1)
        self.pushButtonAM = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonAM.setObjectName(_fromUtf8("pushButtonAM"))
        self.gridLayout_2.addWidget(self.pushButtonAM, 2, 3, 1, 1)
        self.pushButtonCP = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonCP.setObjectName(_fromUtf8("pushButtonCP"))
        self.gridLayout_2.addWidget(self.pushButtonCP, 1, 6, 1, 1)
        self.pushButtonXM = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonXM.setObjectName(_fromUtf8("pushButtonXM"))
        self.gridLayout_2.addWidget(self.pushButtonXM, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 6, 1, 1)
        self.pushButtonYP = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonYP.setObjectName(_fromUtf8("pushButtonYP"))
        self.gridLayout_2.addWidget(self.pushButtonYP, 1, 1, 1, 1)
        self.pushButtonBP = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonBP.setObjectName(_fromUtf8("pushButtonBP"))
        self.gridLayout_2.addWidget(self.pushButtonBP, 1, 5, 1, 1)
        self.pushButtonYM = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonYM.setObjectName(_fromUtf8("pushButtonYM"))
        self.gridLayout_2.addWidget(self.pushButtonYM, 2, 1, 1, 1)
        self.pushButtonAP = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonAP.setObjectName(_fromUtf8("pushButtonAP"))
        self.gridLayout_2.addWidget(self.pushButtonAP, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.pushButtonXP = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonXP.setObjectName(_fromUtf8("pushButtonXP"))
        self.gridLayout_2.addWidget(self.pushButtonXP, 1, 0, 1, 1)
        self.lineEditB = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditB.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditB.setObjectName(_fromUtf8("lineEditB"))
        self.gridLayout_2.addWidget(self.lineEditB, 3, 5, 1, 1)
        self.lineEditY = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditY.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditY.setObjectName(_fromUtf8("lineEditY"))
        self.gridLayout_2.addWidget(self.lineEditY, 3, 1, 1, 1)
        self.lineEditZ = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditZ.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditZ.setObjectName(_fromUtf8("lineEditZ"))
        self.gridLayout_2.addWidget(self.lineEditZ, 3, 2, 1, 1)
        self.pushButtonBM = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonBM.setObjectName(_fromUtf8("pushButtonBM"))
        self.gridLayout_2.addWidget(self.pushButtonBM, 2, 5, 1, 1)
        self.lineEditC = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditC.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditC.setObjectName(_fromUtf8("lineEditC"))
        self.gridLayout_2.addWidget(self.lineEditC, 3, 6, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 46, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        Sensor.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(Sensor)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Sensor.setStatusBar(self.statusbar)

        self.retranslateUi(Sensor)
        QtCore.QMetaObject.connectSlotsByName(Sensor)

    def retranslateUi(self, Sensor):
        Sensor.setWindowTitle(_translate("Sensor", "MainWindow", None))
        self.groupBox.setTitle(_translate("Sensor", "Connection", None))
        self.pushButtonConnect.setText(_translate("Sensor", "Connect", None))
        self.pushButtonDeconnect.setText(_translate("Sensor", "Deconnect", None))
        self.lineEditPort.setText(_translate("Sensor", "6008", None))
        self.lineEditIP.setText(_translate("Sensor", "192.168.1.55", None))
        self.label.setText(_translate("Sensor", "IP :", None))
        self.label_2.setText(_translate("Sensor", "Port :", None))
        self.groupBox_2.setTitle(_translate("Sensor", "Simulate position", None))
        self.pushButtonSend.setText(_translate("Sensor", "Send", None))
        self.lineEditX.setText(_translate("Sensor", "0", None))
        self.lineEditA.setText(_translate("Sensor", "0", None))
        self.pushButtonCM.setText(_translate("Sensor", "-", None))
        self.pushButtonZP.setText(_translate("Sensor", "+", None))
        self.label_7.setText(_translate("Sensor", "B", None))
        self.pushButtonZM.setText(_translate("Sensor", "-", None))
        self.label_10.setText(_translate("Sensor", "A", None))
        self.pushButtonAM.setText(_translate("Sensor", "-", None))
        self.pushButtonCP.setText(_translate("Sensor", "+", None))
        self.pushButtonXM.setText(_translate("Sensor", "-", None))
        self.label_4.setText(_translate("Sensor", "C", None))
        self.pushButtonYP.setText(_translate("Sensor", "+", None))
        self.pushButtonBP.setText(_translate("Sensor", "+", None))
        self.pushButtonYM.setText(_translate("Sensor", "-", None))
        self.pushButtonAP.setText(_translate("Sensor", "+", None))
        self.label_6.setText(_translate("Sensor", "Y", None))
        self.pushButtonXP.setText(_translate("Sensor", "+", None))
        self.lineEditB.setText(_translate("Sensor", "0", None))
        self.lineEditY.setText(_translate("Sensor", "0", None))
        self.lineEditZ.setText(_translate("Sensor", "0", None))
        self.pushButtonBM.setText(_translate("Sensor", "-", None))
        self.lineEditC.setText(_translate("Sensor", "0", None))
        self.label_9.setText(_translate("Sensor", "Z", None))
        self.label_3.setText(_translate("Sensor", "X", None))
        self.label_5.setText(_translate("Sensor", "LIDAR", None))

